remove condition

diff --git a/.github/workflows/test_k8s.yml b/.github/workflows/test_k8s.yml
--- a/.github/workflows/test_k8s.yml
+++ b/.github/workflows/test_k8s.yml
@@ -17,6 +17,15 @@ jobs:
   test-k8s:
     runs-on: ubuntu-latest
     steps:
+      - uses: LouisBrunner/checks-action@v2.0.0
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          name: test k8s
+          status: in_progress
+          output: |
+            {"summary": "",
+            "title": "This check has started..."}
+
       - uses: actions/checkout@v4
 
       - name: Set up Go
@@ -26,49 +35,43 @@ jobs:
 
       - name: Build
         run: make build
-
-      - name: Set up Helm
-        uses: azure/setup-helm@v4.2.0
-        with:
-          version: v3.14.4
-
-      - name: Create k8s Kind Cluster
-        uses: helm/kind-action@v1
-
-      - name: Install KWOK node simulator
-        run: |
-          kubectl apply -f "https://github.com/${KWOK_REPO}/releases/download/${KWOK_LATEST_RELEASE}/kwok.yaml"
-          kubectl apply -f "https://github.com/${KWOK_REPO}/releases/download/${KWOK_LATEST_RELEASE}/stage-fast.yaml"
-          kubectl apply -f https://github.com/${KWOK_REPO}/raw/main/kustomize/stage/pod/chaos/pod-init-container-running-failed.yaml
-          kubectl apply -f https://github.com/${KWOK_REPO}/raw/main/kustomize/stage/pod/chaos/pod-container-running-failed.yaml
-          kubectl apply -f charts/overrides/kwok/pod-complete.yml
-
-      - name: Add virtual nodes to the cluster
-        run: |
-          helm install virtual-nodes charts/virtual-nodes -f charts/virtual-nodes/values-example.yaml
-          kubectl get nodes
-
-      - name: Run knavigator with an example test
-        run: |
-          kubectl create ns k8s-test
-          ./bin/knavigator -tasks resources/tests/k8s/test-job.yml
-          kubectl get job -n k8s-test
       
-      - name: Report tests check
-        if: ${{ github.event.inputs.used-branch && steps.tests-step.outcome }}
-        uses: actions/github-script@v3
+      - name: Fail
+        run: exit 1
+
+      # - name: Set up Helm
+      #   uses: azure/setup-helm@v4.2.0
+      #   with:
+      #     version: v3.14.4
+
+      # - name: Create k8s Kind Cluster
+      #   uses: helm/kind-action@v1
+
+      # - name: Install KWOK node simulator
+      #   run: |
+      #     kubectl apply -f "https://github.com/${KWOK_REPO}/releases/download/${KWOK_LATEST_RELEASE}/kwok.yaml"
+      #     kubectl apply -f "https://github.com/${KWOK_REPO}/releases/download/${KWOK_LATEST_RELEASE}/stage-fast.yaml"
+      #     kubectl apply -f https://github.com/${KWOK_REPO}/raw/main/kustomize/stage/pod/chaos/pod-init-container-running-failed.yaml
+      #     kubectl apply -f https://github.com/${KWOK_REPO}/raw/main/kustomize/stage/pod/chaos/pod-container-running-failed.yaml
+      #     kubectl apply -f charts/overrides/kwok/pod-complete.yml
+
+      # - name: Add virtual nodes to the cluster
+      #   run: |
+      #     helm install virtual-nodes charts/virtual-nodes -f charts/virtual-nodes/values-example.yaml
+      #     kubectl get nodes
+
+      # - name: Run knavigator with an example test
+      #   run: |
+      #     kubectl create ns k8s-test
+      #     ./bin/knavigator -tasks resources/tests/k8s/test-job.yml
+      #     kubectl get job -n k8s-test
+      
+      - uses: LouisBrunner/checks-action@v2.0.0
+        if: always()
         with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            github.checks.create({
-              name: 'run tests',
-              head_sha: '${{ github.event.issue.pull_request.head.sha }}',
-              status: 'completed',
-              conclusion: '${{ steps.tests-step.outcome }}',
-              output: {
-                title: 'Run tests',
-                summary: 'Results: ${{ steps.tests-step.outcome }}'
-              },
-              owner: context.repo.owner,
-              repo: context.repo.repo
-            })
+          token: ${{ secrets.GITHUB_TOKEN }}
+          name: test k8s
+          status: completed
+          conclusion: ${{ job.status }}
+          output: |
+            {"summary":"${{ steps.test.outputs.summary }}"}
